### ISSUE TITLE
Capture host's real hostname for container's beat.hostname

### ISSUE THREAD

**Issue by jamie1911** [logzio/docker-collector-logs#12]
Using AWS ECS, we have multiple EC2 hosts running our containers. We are sending the logs to logzio via the docker-collector-logs container and I can see my container logs perfectly. However, if I am setting alerts based on the log errors I receive, it is hard to figure out which EC2 host is hosting the problematic container where the logs are getting generated. The field beat.hostname and beat.name appears to be some random string that is not the instanceId.

Is there something I can do to get the beat.hostname of the container to be the real host's hostname?

**Comment by jamie1911** [comment]
After looking at the code for filebeat-yml-script.py, I think I could do something like this in the startup script.

`DOCKERHOST=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)

 /usr/bin/docker run -dit \
                                     --restart unless-stopped \
                                     --name logzio \
                                     --env LOGZIO_TOKEN="${LogzioToken}" \
                                     --env LOGZIO_URL="${LogzioURL}" \
                                     --env LOGZIO_CODEC="json" \
                                     --env additionalFields="docker.host.hostname=$DOCKERHOST" \
                                     --env skipContainerName="logzio,ecs-agent" \
                                  -v /var/run/docker.sock:/var/run/docker.sock:ro \
                                  -v /var/lib/docker/containers:/var/lib/docker/containers \
                              logzio/docker-collector-logs
`

Does my assumption make sense?

**Comment by idohalevi** [comment]
@jamie1911 Thank you for the detailed description, it helps a lot! we'll go over it and get back to you. The solution you offered works for you?

**Comment by jamie1911** [comment]
> @jamie1911 Thank you for the detailed description, it helps a lot! we'll go over it and get back to you. The solution you offered works for you?

I am going to test the idea this week and I'll report back how it goes.

**Comment by jamie1911** [comment]
I was able to add the following into the userdata section for my ECS AMI.

```
              DOCKERINSTANCE=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)

              # Start the Logz.io container
              /usr/bin/docker run -dit \
                                     --restart unless-stopped \
                                     --name logzio \
                                     --env LOGZIO_TOKEN="${LogzioToken}" \
                                     --env LOGZIO_URL="${LogzioURL}" \
                                     --env LOGZIO_CODEC="json" \
                                     --env DOCKERINSTANCE=$DOCKERINSTANCE \
                                     --env additionalFields="docker.host.instance=$DOCKERINSTANCE" \
                                     --env skipContainerName="logzio,ecs-agent" \
                                  -v /var/run/docker.sock:/var/run/docker.sock:ro \
                                  -v /var/lib/docker/containers:/var/lib/docker/containers \
                              logzio/docker-collector-logs
```
This seems to work correctly. When AWS spins up new EC2 instances for the ECS tasks, the following get configured in the logzio docker sidecar container:

```
  fields:
    token: KEY
    logzio_codec: json
    type: docker-collector-logs
    docker.host.instance: i-0a353f4asfsdfsd
  ignore_older: 3h

```
logs in the logzio console now contain a field as such:
docker.host.instance | i-0a353f4asfsdfsd

**Comment by idohalevi** [comment]
@jamie1911 Nice. Correct me if I'm wrong, but I don't see a need to change the code to support it

**Comment by jamie1911** [comment]
> @jamie1911 Nice. Correct me if I'm wrong, but I don't see a need to change the code to support it

agreed!
