### ISSUE TITLE
how to change the paths to collect logs?

### ISSUE THREAD

**Issue by masterchop** [logzio/docker-collector-logs#21]
I just setup a container with this docker file and works as expected but i  dont see a way to setup the path on the filebeat.yml file.
I am able to add additional Fields but that just create another field called paths. Is there any way to change it before deployment?

This is the default everytime:

```
filebeat.inputs:
- type: container
  **paths:
  - /var/lib/docker/containers/*/*.log**
  fields_under_root: true
```

Thanks

**Comment by Doron-Bargo** [comment]
Hi @masterchop 
At the moment we don't have an option to change the path.
You can build a new docker using a different path or if you have time you can open a PR that add this kind of option and we will review it shortly

**Comment by masterchop** [comment]
yes, at the end i end up using volumes to do the work but thanks.
