### ISSUE TITLE
Allow adding extra fields to log messages through environment variables

### ISSUE THREAD

**Issue by yakirsudry** [logzio/docker-collector-logs#8]
We wish to add some specific "environment=..." to the log collection per environment.
The containers themselves are unaware of the environment they are set on, so it probably should be set here, in the collector.

I guess having some LOGZIO_XXXX=yyy       translated to     XXXX=yyy     in messages is a simple solution

**Comment by idohalevi** [comment]
@yakirsudry What data are from your environment are you missing in the log?

**Comment by yakirsudry** [comment]
the name of the environment (The name I use for it. e.g "staging-3").
And potentially other fields I want to add for the environment (e.g ENVIRONMENT_VERSION_HASH)

**Comment by idohalevi** [comment]
#9
